apiVersion: v1
kind: Pod
metadata:
  name: front
  labels:
    app.kubernetes.io/name: front
spec:
  containers:
    - name: front
      image: "51.159.160.76:8081/crossy-job-front/xxx"
      ports:
        - name: front-http
          containerPort: 3000
      resources:
        limits:
          memory: "256Mi"
